[tool.flake8]
    max-line-length = 120

[tool.mypy]
    disallow_any_explicit = true
    disallow_any_generics = true
    disallow_subclassing_any = true
    disallow_untyped_defs = true
    check_untyped_defs = true
    warn_unused_ignores = true
    warn_return_any = true
    warn_unreachable = true
